Allow for revealing votes while waiting for votes
moorscode/scrum-poker pull request #39
Opened 2020-12-06 14:22 UTC by diedexx

![image](https://user-images.githubusercontent.com/5352634/101282588-5431a200-37d6-11eb-9147-ce3e3fe6d578.png)

If you're waiting for somebody who is AFK or unable to cast a vote, you can press the 'Reveal votes' button, which first asks for confirmation:

![image](https://user-images.githubusercontent.com/5352634/101282593-598eec80-37d6-11eb-9ef5-850e3f33304d.png)

After which, all known votes are shown
![image](https://user-images.githubusercontent.com/5352634/101282596-60b5fa80-37d6-11eb-8193-d3c68fbfc8ec.png)

---

Also included in this pr:
- Auto-format most of the Vue code according to new CS settings
- Fix the margin-left:0 on both the first choice button and result block

2020-12-06 15:08 UTC, moorscode requested changes
Great PR! Hope this feature doesn't have to be used too often, but nice to have 👍 

Some naming ideas.
Suggestion to reduce templating code.

2020-12-06 15:08 UTC, moorscode commented on html/index.html
> +					<div class="reveal-votes">
^ this seems like strange identation, perhaps it still kept spaces vs tabs for some lines 🤔

2020-12-06 15:08 UTC, moorscode commented on src/pokers/poker-room.ts
> +	public getNotVotedClients():Client[] {
Suggested name: `getVotePendingClients`

2020-12-06 15:08 UTC, moorscode commented on src/pokers/poker-room.ts
> +	public getRealVotesWithObscuredVotes( story: Story ): Vote[] {
Suggested name: `getUnobscuredVotes`
Pending votes cannot be 'obscured' because there is no vote, I think this name fits the purpose better.

2020-12-06 15:08 UTC, moorscode commented on src/pokers/poker-room.ts
> +				( client: Client ): ObscuredVote =>  this.getObscuredVote( this.currentStory, client ),
```suggestion
				( client: Client ): ObscuredVote => this.getObscuredVote( this.currentStory, client ),
```

2020-12-06 15:08 UTC, moorscode commented on src/pokers/poker-room.ts
> +			( client: Client ): ObscuredVote =>  this.getObscuredVote( story, client ),
```suggestion
			( client: Client ): ObscuredVote => this.getObscuredVote( story, client ),
```

2020-12-10 19:30 UTC, diedexx commented
Great suggestions! Especially the computed methods clean things up a bit

2020-12-11 21:12 UTC, merged

2020-12-11 21:12 UTC, moorscode commented
Added: If you haven't voted yourself you should not be able to reveal votes.